# ----------------------------------------------------------------------------
# Trivadis AG, Infrastructure Managed Services
# Saegereistrasse 29, 8152 Glattbrugg, Switzerland
# ----------------------------------------------------------------------------
# Name.......: mdlint.yaml 
# Author.....: Stefan Oehrli (oes) stefan.oehrli@trivadis.com
# Editor.....: Stefan Oehrli
# Date.......: 2021.02.23
# Revision...: 
# Purpose....: Markdown lint workflow for GitHub
# Notes......: --
# Reference..: https://github.com/DavidAnson/markdownlint
#              https://github.com/DavidAnson/markdownlint-cli2-action
# ----------------------------------------------------------------------------
name: markdown-lint

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'

  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
#   check:
#     name: Check Markdown Lint
#     runs-on: ubuntu-latest
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2
#       - name: markdownlint-cli2-action
#         # You may pin to the exact commit or the version.
#         # uses: DavidAnson/markdownlint-cli2-action@df5e41bfe87014dffa695c68b9fb66565e43140a
#         uses: DavidAnson/markdownlint-cli2-action@v2
#         with:
#           globs: |
#             **/*.md
#             ! CHANGELOG.md

  Check_Docs:
    name: Check Markdown using markdownlint-cli
    runs-on: ubuntu-latest
    steps:
      # Check Markdown using markdownlint-cli from docker images 06kellyjac/markdownlint-cli
      - name: run markdownlint-cli
        uses: docker://06kellyjac/markdownlint-cli
        with:
<<<<<<< HEAD
          args: >-
            .
=======
          args: .
>>>>>>> e534c59e2b8227b42417349803a00d9041305483
# --- EOF -------------------------------------------------------------------
