# ----------------------------------------------------------------------------
# Trivadis AG, Infrastructure Managed Services
# Saegereistrasse 29, 8152 Glattbrugg, Switzerland
# ----------------------------------------------------------------------------
# Name.......: mdlint.yaml 
# Author.....: Stefan Oehrli (oes) stefan.oehrli@trivadis.com
# Editor.....: Stefan Oehrli
# Date.......: 2021.02.23
# Revision...: 
# Purpose....: Markdown lint workflow for GitHub
# Notes......: --
# Reference..: https://github.com/DavidAnson/markdownlint
# ----------------------------------------------------------------------------
# This is a basic workflow to help you get started with Actions

name: pandoc

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'

  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: oehrlis/pandoc
<<<<<<< HEAD
      options: -v "$PWD":/workdir:z
=======
>>>>>>> ebbad839d1a37d2125c852926dbdb87fbaa3de58
    steps:  
    - uses: actions/checkout@v2
    - name: Pandoc Help
      run:  -v "$PWD":/workdir:z pandoc --metadata-file=en/metadata.yml -o test.pdf ?x??-*.md
    - name: Pandoc Version
      run: pandoc --version

# --- EOF -------------------------------------------------------------------
