# ----------------------------------------------------------------------------
# Trivadis AG, Infrastructure Managed Services
# Saegereistrasse 29, 8152 Glattbrugg, Switzerland
# ----------------------------------------------------------------------------
# Name.......: mdlint.yaml 
# Author.....: Stefan Oehrli (oes) stefan.oehrli@trivadis.com
# Editor.....: Stefan Oehrli
# Date.......: 2021.02.23
# Revision...: 
# Purpose....: Markdown lint workflow for GitHub
# Notes......: --
# Reference..: https://github.com/DavidAnson/markdownlint
# ----------------------------------------------------------------------------
name: pandoc
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'

  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# jobs:
  # build_documents:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: |
  #         mkdir output  
  #         echo "md_files=$(printf '%s ' en/?x??-*.md)" >> $GITHUB_ENV
  #     - uses: docker://oehrlis/pandoc
  #       with:
  #         args: --pdf-engine=xelatex --to=pdf --metadata-file=en/metadata.yml --output=output/result.pdf ${{ env.md_files }}
  #         args: >-
  #           --pdf-engine=xelatex 
  #           --metadata-file=en/metadata.yml 
  #           --output=result.pdf ${{ env.md_files }}      
  #     - uses: actions/upload-artifact@master
  #       with:
  #         name: build_documents
  #         path: result.pdf


jobs:
  build_documents:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "md_files=$(printf '%s ' en/?x??-*.md)" >> $GITHUB_ENV
      - uses: docker://oehrlis/pandoc
        with:
          args: >-
            --pdf-engine=xelatex 
            --metadata-file=en/metadata.yml 
            --output=trivadis-good-practice-template_EN.pdf ${{ env.md_files }}
      - uses: actions/upload-artifact@master
        with:
          name: build_documents
          path: trivadis-good-practice-template_??.pdf
# --- EOF -------------------------------------------------------------------
